### ISSUE TITLE
Forecast ID, Run ID and Forecast Match ID misunderstanding

### ISSUE THREAD

**Issue by e-lo** [e-lo/forecastcarddata#14]
Forecast ID  should be a unique identifier w/in a forecast csv.

Forecast match ID should be what is used to match the row in the forecast to row in the observation.

Run ID is the model run, so if a model run is "opening year" it should be a different model run than "design year" (unless it is a type of model that forecasts both at the same time).

```
# OhioDOT21927ROS-35-14-40/forecasts/forecast-21927.csv
forecast_id,run_id,poi_id,forecast_match_id,start_time,end_time,forecast_variable,forecast_value
f1,1,21927-1137,Opening Year,00:00:00,23:59:59,volume,9250
f3,1,21927-1137,Design Year,00:00:00,23:59:59,volume,11310
f1,1,21927-1158,Opening Year,00:00:00,23:59:59,volume,12450
``` 

**Duplicate `forecast_id`

**Comment by jawadmhoque** [comment]
Addressed in the latest commit.
