### ISSUE TITLE
many poi cards (and others) have double-commas.

### ISSUE THREAD

**Issue by e-lo** [e-lo/forecastcarddata#3]
The CSV reader doesn't like them and I think they were probably written by mistake.

![image](https://user-images.githubusercontent.com/794787/50869365-8a571480-1368-11e9-822e-94b3b3d0743e.png)

**Comment by jawadmhoque** [comment]
Rmoved the double commas and other special characters from string.

**Comment by e-lo** [comment]
LGTM
