### ISSUE TITLE
run id missing in many scenario files

### ISSUE THREAD

**Issue by e-lo** [e-lo/forecastcarddata#5]
It is a required field.

i.e. `OhioDOT21616HAN-75-3-22/scenarios-21616.csv`

**Comment by jawadmhoque** [comment]
Run ID added in the scenario files. 
![image](https://user-images.githubusercontent.com/35570340/51850716-4fedf100-22f0-11e9-8b6e-6a48ace036be.png)

**Comment by e-lo** [comment]
LGTM
