### ISSUE TITLE
Year in Project File should be int, not float

### ISSUE THREAD

**Issue by e-lo** [e-lo/forecastcarddata#8]
Right now the horizon year field is being printed as a float, i.e. `2007.0` ; needs to be an int or a year.

**Comment by jawadmhoque** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/35570340/51920425-5beeb700-23b3-11e9-93d7-d2c7f37963c4.png)

**Comment by e-lo** [comment]
Whatever you did here worked!
